development_org: &defaults
  client_id: xxxxxx.apps.googleusercontent.com
  client_secret: xxxxxx
  scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  redirect_uri: http://localhost/connect/google
  authorization_endpoint: https://accounts.google.com/o/oauth2/auth
  token_endpoint: https://accounts.google.com/o/oauth2/token
  check_session_endpoint: https://accounts.google.com/o/oauth2/tokeninfo
  userinfo_endpoint: https://www.googleapis.com/oauth2/v1/userinfo
  
development: &defaults
  client_id: xxxxxx.apps.googleusercontent.com
  client_secret: xxxxxx
  scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  redirect_uri: http://localhost:3000/connect/google
  authorization_endpoint: https://accounts.google.com/o/oauth2/auth
  token_endpoint: https://accounts.google.com/o/oauth2/token
  check_session_endpoint: https://accounts.google.com/o/oauth2/tokeninfo
  userinfo_endpoint: https://www.googleapis.com/oauth2/v1/userinfo

test:
  <<: *defaults

production:
  <<: *defaults
  redirect_uri: https://connect-op.heroku.com/connect/google
